### ISSUE TITLE
Hit skill buttons periodicly

### ISSUE THREAD

**Issue by luckydonald** [Shadowspaz/NIAutoclicker#2]
The cooldown buttons should be activated once per minute, either via 1-9 keys or via click

**Comment by luckydonald** [comment]
Probably a possibility to define a second click cycle which is executed only once a minute (or once the other on is executed 10 times) would be great.

**Comment by Shadowspaz** [comment]
I've played with this, and it really bogs down the clicker- Either AHK can't handle multiple clickers too well, or my computer can't. Regardless, there was definitely a drop in performance.

So what I do instead is just specify a click cycle with multiple hits in the same place- For example, 9 on monster, 1 on level up, at 50cps, would click the monster 45 times a second, and level up your hero 5 times a second.
